provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  go-echo:
    lang: golang-http
    handler: ./go-echo
    image: alexellis2/go-echo:0.2
    environment:
      write_debug: true
    annotations:
      topic: vm.powered.on
