provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  go-echo:
    lang: golang-http
    handler: ./go-echo
    image: alexellisuk/go-echo:0.2.2
    environment:
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
